name: Publish eggwrap to PyPI

on: push

jobs:
  build:
    name: Build eggwrap
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions-rust-lang/setup-rust-toolchain@v1
        name: Setup rust toolchain

      - name: Install pypa/build and maturin
        run: >-
          python3 -m
          pip install
          build maturin
          --user

      - name: Install CBC Solver
        run: sudo apt-get install -y coinor-cbc coinor-libcbc-dev

      - name: Build with Maturin
        uses: PyO3/maturin-action@v1
        with:
          command: build
          args: --release

      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions-${{ matrix.python-version }}
          path: target/wheels/


  publish-to-pypi:
    name: Publish eggwrap to PyPI

    needs:
      - build

    runs-on: ubuntu-latest

    environment:
      name: release
      url: https://pypi.org/p/eggwrap

    permissions:
      id-token: write  # IMPORTANT: mandatory for trusted publishing

    steps:
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions-${{ matrix.python-version }}
          path: dist/
      - name: Publish distribution 📦 to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1